---
title: "support"
author: "Juan felipe Múnera Vergara"
date: "8/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read.csv("dataset_tae_final_no_na.csv")
data2 <- read.csv("test_tae_no_na.csv")

levels(data$native_country) <- c(levels(data$native_country),"other")
levels(data2$native_country) <- c(levels(data2$native_country),"other")
data[!(data$native_country%in%c(" United-States"," Mexico")), ]$native_country <- "other"
data2[!(data2$native_country%in%c(" United-States"," Mexico")), ]$native_country <- "other"

```


```{r}
table(data$ocupation)

```

```{r}
table(data2$marital_status)
table(data$relationship)

levels(data$marital_status) <- c(levels(data$marital_status),"Married")
levels(data2$marital_status) <- c(levels(data2$marital_status),"Married")

data[data$marital_status%in% c(" Married-AF-spouse", " Married-civ-spouse", " Married-spouse-absent"),]$marital_status <- "Married"
data2[data2$marital_status%in% c(" Married-AF-spouse", " Married-civ-spouse", " Married-spouse-absent"),]$marital_status <- "Married"
```

```{r}
library(dplyr)
data%>%group_by(workclass, income)%>%summarise(n = n())
levels(data$workclass)

data <- data[-(data$workclass==" Without-pay"),]
data2 <- data2[-(data$workclass==" Without-pay"),]
```
```{r}
write.csv(data, "data_set_tae_final_no_na_mod.csv", row.names = F)
write.csv(data, "test_no_na_mod.csv", row.names = F)
```

